# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
    - '&l ɪᴍᴘᴇʀɪᴜᴍ #D1D1D1| #FFC01A&lᴀ#FF9A30&lᴜ#FF7347&lʀ#FF4D5D&lᴏ#FF2674&lʀ#FF008A&lᴀ '
    - '&fᴘʟᴀʏᴇʀs ᴏɴʟɪɴᴇ #58FF38&l%online%'
  footer: null
  disable-condition: '%world%=disabledworld'
  per-world:
    world1:
      header:
        - an example of world with custom
      footer:
        - header/footer and prefix/suffix
    world2;world3:
      header:
        - This is a shared header for
        - world2 and world3
  per-server:
    server1:
      header:
        - an example of server with custom header
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
    - GROUPS:owner,admin,srmod,mod,helper,srdev,dev,trialdev,booster,media,builder,cleaner,tier10,tier9,tier8,tier7,tier6,tier5,tier4,tier3,tier2,tier1,default,afkers
    - PERMISSIONS:group.diamond3,group.diamond2,group.diamond1,group.gold3,group.gold2,group.gold1,group.lapis3,group.lapis2,group.lapis1,group.redstone2,group.redstone1,group.iron2,group.iron1,group.coal2,group.coal1,group.stone1,group.dirt1
    - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
playerlist-objective:
  enabled: false
  value: '***'
  fancy-value: '&7Ping: %ping%'
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  fancy-display-players: '&c%health%'
  fancy-display-default: NPC
  disable-condition: '%world%=disabledworld'
prevent-spectator-effect:
  enabled: true
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  scoreboards:
    scoreboard-1.20.3+:
      title: <#E0B11E>Imperium</#FF0000>
      display-condition: '%player-version-id%>=765'
      lines:
        - '&7%date%'
        - '%animation:MyAnimation1%'
        - '&6Online:'
        - '* &eOnline&7:||%online%'
        - '* &eCurrent World&7:||%worldonline%'
        - ''
        - '&6Personal Info:'
        - '* &b&lRank&7:||%luckperms_prefix%'
        - '* &b&lPing&7:||%ping%&8ms'
        - '* &b&lMark&7:||%headsplus_level%'
        - '* &b&lBal&7: ||&6%lighteconomy_money%'
        - '%animation:MyAnimation1%'
    scoreboard:
      title: <#E0B11E>MyServer</#FF0000>
      lines:
        - '&7%date%'
        - '%animation:MyAnimation1%'
        - '&6Online:'
        - '* &eOnline&7: &f%online%'
        - '* &eCurrent World&7: &f%worldonline%'
        - '* &eStaff&7: &f%staffonline%'
        - ''
        - '&6Personal Info:'
        - '* &bRank&7: &f%group%'
        - '* &bPing&7: &f%ping%&8ms'
        - '* &bWorld&7: &f%world%'
        - '%animation:MyAnimation1%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
        - '1|&3Website&f:'
        - 2|&bmyserver.net
        - '3|&8&m                       '
        - '4|&3Name&f:'
        - 5|&b%player%
        - '7|&3Rank&f:'
        - '8|Rank: %group%'
        - '10|&3World&f:'
        - 11|&b%world%
        - '13|&3Time&f:'
        - 14|&b%time%
        - '21|&3Teamspeak&f:'
        - 22|&bts.myserver.net
        - '23|&8&m                       '
        - '41|&3Store&f:'
        - 42|&bshop.myserver.net
        - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
            - 24-40
        players:
          slots:
            - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
      - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
  - Owner
  - Admin
  - Mod
  - Helper
  - default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
    - ignoredworld
    - build
  shared-playerlist-world-groups:
    lobby:
      - lobby1
      - lobby2
    minigames:
      - paintball
      - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
    - spyserver1
    - spyserver2
  server-groups:
    lobbies:
      - lobby1
      - lobby2
    group2:
      - server1
      - server2
  update-latency: false
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
permission-refresh-interval: 1000
enable-redisbungee-support: true